name: Continuous deployment

on:
  schedule:
    - cron: '0 0 * * 6,2' # Saturday and Tuesday at midnight

jobs:
  test-deploy:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint
      - run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs:
      - test-deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - run: npm ci
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: 'public'