name: Node continuous integration

on: [push]

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint
      - run: npm run test
