name: Test pull requests

on: pull_request

jobs:
  test-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint
      - run: npm run test
  merge-dependabot:
    name: Merge me!
    needs:
      - test-pull
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v1
        with:
          GITHUB_LOGIN: dependabot[bot]
          # This must be used as GitHub Actions token does not support
          # pushing to protected branches.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  bump-package-version:
    if: github.actor == 'dependabot[bot]'
    name: Bumps as a patch
    needs:
      - merge-dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: phips28/gh-action-bump-version@v8.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}