name: Test pull requests

on: pull_request

jobs:
  test-pull:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      - run: npx pnpm i
      - run: npm run lint
      - run: npm run test